channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas=2.3.2
  - seaborn=0.13.2
  - numpy=2.3.2
  - samtools=1.22.1
  - pysam=0.23.3
  - python-edlib=1.3.9.post1
  - fastp=1.0.1
  - star=2.7.11b
  - awscli=2.28.22
  - pigz=2.8
